######################################################################
# Automatically generated by qmake (2.01a) dom ago 29 21:15:16 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GUISencilla.h
SOURCES += GUISencilla.cpp main.cpp
