######################################################################
# Automatically generated by qmake (2.01a) qua abr 20 16:16:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PostgreSQLConection.h
SOURCES += Main.cpp PostgreSQLConection.cpp

QT += sql
