######################################################################
# Automatically generated by qmake (2.01a) qua abr 20 15:18:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MysqlConection.h
SOURCES += Main.cpp MysqlConection.cpp

QT += sql
