######################################################################
# Automatically generated by qmake (2.01a) dom ago 29 21:14:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BasicoQT.h
SOURCES += BasicoQT.cpp main.cpp
